# Generated by Django 3.2.5 on 2021-07-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent_Child',
            new_name='Edge',
        ),
        migrations.RenameModel(
            old_name='Query',
            new_name='Node',
        ),
        migrations.AlterModelOptions(
            name='edge',
            options={'verbose_name': 'Edges', 'verbose_name_plural': 'Edges'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.RemoveConstraint(
            model_name='edge',
            name='unique_parent_child',
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_edge'),
        ),
    ]
