# Generated by Django 3.2.5 on 2021-07-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210722_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='relevance',
            new_name='weight',
        ),
    ]
