# Generated by Django 3.2.5 on 2021-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210722_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='date_children_last_pulled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
