# Generated by Django 3.2.5 on 2021-07-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_node_date_children_last_pulled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_child', to='search.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_parent', to='search.node'),
        ),
    ]
